//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolPortalAPI.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marks
    {
        public int Id { get; set; }
        public int StudentId { get; set; }
        public int LessonId { get; set; }
        public string Mark { get; set; }
        public string Comment { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Lessons Lessons { get; set; }
        public virtual User User { get; set; }
    }
}
